[package]
name = "cloudmusic-macmedia"
version = "0.1.0"
authors = ["YXL <chenxin.lan.76@gmail.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
winit = "0.26"

[dependencies.souvlaki]
git = "https://github.com/YXL76/souvlaki"
branch = "deps"
